[workspace]
members = [
	"crates/grapheme-artifact",
	"crates/grapheme-compiler",
	"crates/grapheme-runtime",
	"crates/grapheme-cli",
	"crates/grapheme-lsp",
]
exclude = ["plugins/core-echo-rs", "plugins/io-rs", "plugins/http-rs", "plugins/memory-rs", "plugins/tcp-rs", "plugins/smtp-rs", "plugins/secrets-rs"]
default-members = ["crates/grapheme-cli"]
resolver = "2"
