[package]
name = "grapheme-lsp"
version = "0.3.0"
edition = "2021"
description = "Language Server Protocol implementation for Grapheme"
license = "Apache-2.0"
repository = "https://github.com/entasislabs/grapheme"
homepage = "https://github.com/entasislabs/grapheme"

[[bin]]
name = "grapheme-lsp"
path = "src/main.rs"

[dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread", "io-std"] }
tower-lsp = "0.20"
grapheme-compiler = { path = "../grapheme-compiler", version = "0.2.0" }
grapheme-signatures = { path = "../grapheme-signatures", version = "0.2.0" }
